# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9894a148bb2cf23a0138f435e6aa4c176377d28b2d59fef2bc93eb1ac6fbe6facc35ce19e0e1b8fa2d82ddc920e4c8495518bfbb2218b3c1ca01bf4456a80ccd

test:
  secret_key_base: a4a2d3f8b86dffd8764937e47efd1666c9a534635dd76abcc124c8c656b3fd592f670e5e1628ac11bfbe7b225c63c42265fe7703b8f73f328d95a15e5e710ce6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
